### ISSUE TITLE
not working with latest NVDA threshold

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/focusHighlight#14]
version 6.1-dev #3 

```
INFO - core.main (21:07:36.733):
NVDA version threshold-17459,ef3ed13f

ERROR - globalPluginHandler.listPlugins (21:06:15.947):
Error importing global plugin focusHighlight
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 22, in listPlugins
  File "D:\Applications\nvda_th\userConfig\addons\focusHighlight\globalPlugins\focusHighlight.py", line 25, in <module>
ImportError: No module named validate
```

**Comment by nishimotz** [comment]
```
ERROR - globalPluginHandler.listPlugins (15:41:05.836):
Error importing global plugin focusHighlight
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 22, in listPlugins
  File "C:\Users\nishimotz\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 30, in <module>
ImportError: No module named win32con
```

**Comment by nishimotz** [comment]
tested with NVDA version threshold-17459,ef3ed13f.
https://www.dropbox.com/s/1ou445qwn9apjr4/focusHighlight-6.1-dev-190605.nvda-addon?dl=0

**Comment by nishimotz** [comment]
Version 6.1 is out.
https://github.com/nvdajp/focusHighlight/releases/tag/6.1
