### ISSUE TITLE
Windows 10 setting raises error

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/focusHighlight#8]
FH 5.0-dev + NVDA 2017.3jp-beta-170707 + Windows 10 (32bit) build 15063.413

* press Windows+I to open Windows 10 Settings.
* press Tab, press Enter to open System.
* press Shift+Tab, press Enter to open Setting home again. This raises error as follows:

```
ERROR - unhandled exception (18:23:18.500):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\Users\nishimotz\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 490, in wndProc
  File "C:\Users\nishimotz\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 395, in updateFocusLocation
  File "C:\Users\nishimotz\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 350, in moveAndShowWindow
ArgumentError: argument 5: <type 'exceptions.OverflowError'>: long int too long to convert
```

**Comment by nishimotz** [comment]
FH 5.3-dev + NVDA 2018.3.2jp + Windows 10 (64bit) build 17134.320

Cannot reproduce the issue.
